version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  foodkmbackend:
    ports:
      - "3423:3423"
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile.backend
    networks:
      - elk
    environment:
      - N_WORKERS=2
      - PORT=3423
      - FOODKM_ES_HOST=elasticsearch
      - FOODKM_ES_PORT=9200

networks:
  elk:
    driver: bridge
