const productsInit = [
    {
      "additives": 14,
      "address": "24950 Vidanes, León, Spain",
      "address_type": "supplier",
      "allergens": [],
      "category_child1": "ARROZ Y LEGUMBRES",
      "category_child2": "LEGUMBRES COCIDAS",
      "category_root": "ALIMENTACION",
      "co2": 2895.1570977024357,
      "country": "Spain",
      "date_inserted": "2019-03-29T11:37:54.044867",
      "distance": 289.5157097702436,
      "locality": "Vidanes",
      "location": {
        "lat": 42.76359850000001,
        "lon": -5.1402749000000005
      },
      "postal_code": 24950,
      "price": 0.79,
      "price_netto": " 1,98 Euros",
      "price_norm": "1 KILO: 1,98 Euros",
      "product_amount_netto": "570 g",
      "product_brand": "Hacendado",
      "product_description": " GARBANZO COCIDO PEDROSILLANO, HACENDADO, TARRO 570 g ESCURRIDO 400 g",
      "product_description_short": "Garbanzo pedrosillano Hacendado 570 g",
      "product_name": "Garbanzo pedrosillano",
      "product_price_netto": 1.98,
      "product_quantity_netto": "1 KILO",
      "provider_address": "Pol. Ind. de Cistierna, P-32. 24950 Vidanes - León",
      "provider_country": "España",
      "provider_ean_id": 8480000260338,
      "provider_name": "Selección de Productos Leoneses,SA",
      "province": "León",
      "state": "Castilla y León",
      "active": false
    },
    {
      "additives": 0,
      "address": "Los Angeles, CA, USA",
      "address_type": "origin",
      "allergens": [
        "soja"
      ],
      "category_child1": "ARROZ Y LEGUMBRES",
      "category_child2": "LEGUMBRES SECAS",
      "category_root": "ALIMENTACION",
      "co2": 93654.0163714616,
      "country": "United States",
      "date_inserted": "2019-03-29T11:37:54.044867",
      "distance": 9365.40163714616,
      "ingredients": "garbanzo pedrosillano. las legumbres son un componente esencial de la dieta mediterránea. garbanzo pedrosillano",
      "locality": "Los Angeles",
      "location": {
        "lat": 34.0522342,
        "lon": -118.24368490000002
      },
      "price": 1.99,
      "price_norm": "unknown",
      "product_amount_netto": "1 KG",
      "product_brand": "Hacendado",
      "product_description": " GARBANZO PEDROSILLANO, HACENDADO, PAQUETE 1 kg",
      "product_description_short": "Garbanzo Pedrosillano Hacendado 1 Kg",
      "product_name": "Garbanzo Pedrosillano",
      "provider_address": "Polígono Industrial de Cistierna. 24950 Vidanes - León",
      "provider_country": "Estados Unidos (los)",
      "provider_ean_id": 8480000052193,
      "provider_name": "SEPROLESA",
      "province": "Los Angeles County",
      "state": "California"
    },
    {
      "additives": 0,
      "address": "24815, León, Spain",
      "address_type": "supplier",
      "allergens": [
        "soja",
        "lactosa"
      ],
      "category_child1": "ARROZ Y LEGUMBRES",
      "category_child2": "LEGUMBRES SECAS",
      "category_root": "ALIMENTACION",
      "co2": 2876.2464792061373,
      "country": "Spain",
      "date_inserted": "2019-03-29T11:37:54.044867",
      "distance": 287.6246479206137,
      "ingredients": "garbanzo lechoso. las legumbres son un componente esencial de la dieta mediterránea. garbanzo lechoso",
      "location": {
        "lat": 42.747161,
        "lon": -5.133434299999999
      },
      "postal_code": 24815,
      "price": 2.39,
      "price_norm": "unknown",
      "product_amount_netto": "1 KG",
      "product_brand": "Hacendado",
      "product_description": " GARBANZO LECHOSO ANDALUZ, HACENDADO, PAQUETE 1 kg",
      "product_description_short": "Garbanzo Lechoso Andaluz Hacendado 1 Kg",
      "product_name": "Garbanzo Lechoso Andaluz",
      "provider_address": "Polígono Industrial de Cistierna. 24950 Vidanes - León",
      "provider_country": "España",
      "provider_ean_id": 8480000052209,
      "provider_name": "SEPROLESA",
      "province": "León",
      "state": "Castile and León",
      "active": false
    },
    {
      "additives": 10,
      "address": "Pol. Ind., Parcela C, 31560 Azagra, Navarra, Spain",
      "address_type": "supplier",
      "allergens": [
        "cerbada",
        "gluten",
        "soja"
      ],
      "category_child1": "VERDURAS",
      "category_child2": "VERDURAS Y LEGUMBRES SIMPLES",
      "category_root": "CONGELADOS",
      "co2": 2596.8410073219643,
      "country": "Spain",
      "date_inserted": "2019-03-29T11:40:02.471519",
      "distance": 259.68410073219644,
      "ingredients": "garbanzos. *el contenido de sal obedece exclusivamente al sodio presente de forma natural en el alimento. garbanzos",
      "locality": "Azagra",
      "location": {
        "lat": 42.31720900000001,
        "lon": -1.903016
      },
      "postal_code": 31560,
      "price": 1.05,
      "price_netto": " 2,33 Euros",
      "price_norm": "1 KILO: 2,33 Euros",
      "product_amount_netto": "450 g",
      "product_brand": "Hacendado",
      "product_description": " GARBANZO CONGELADO, HACENDADO, PAQUETE 450 g",
      "product_description_short": "Garbanzos ultracongelados",
      "product_name": "Garbanzos ultracongelados",
      "product_price_netto": 2.33,
      "product_quantity_netto": "1 KILO",
      "provider_address": "Polígono Industrial, Parcela C. 31560 Azagra (Navarra), España. info@virto.es",
      "provider_ean_id": 8480000612724,
      "provider_name": "Ultracongelados Virto, S.A.",
      "province": "Navarra",
      "state": "Navarra",
      "active": false
    },
    {
      "additives": 2,
      "address": "Edisonstraat 2, 2171 TV Sassenheim, Netherlands",
      "address_type": "supplier",
      "allergens": [
        "lactosa",
        "gluten",
        "soja"
      ],
      "category_child1": "PLATOS PREPARADOS",
      "category_child2": "REFRIGERADOS",
      "category_root": "ALIMENTACION",
      "co2": 14536.9704640811,
      "country": "Netherlands",
      "date_inserted": "2019-03-29T11:38:15.525103",
      "distance": 1453.69704640811,
      "locality": "Sassenheim",
      "location": {
        "lat": 52.2129436,
        "lon": 4.4936812
      },
      "postal_code": "2171 TV",
      "price": 1.9,
      "price_netto": " 11,88 Euros",
      "price_norm": "1 KILO: 11,88 Euros",
      "product_amount_netto": "160 g",
      "product_brand": "Hacendado",
      "product_description": " COMIDA PREPARADA FALAFEL (CROQUETA DE GARBANZO) CON SALSA TAHINA, , TARRINA 160 g",
      "product_description_short": "Falafel con Salsa Tahina Hacendado 160 g",
      "product_name": "Falafel con Tahina",
      "product_price_netto": 11.88,
      "product_quantity_netto": "1 KILO",
      "provider_address": "Edisonstraat 2, 2171 TV Sassenheim, Países Bajos",
      "provider_ean_id": 8710378562162,
      "provider_name": "Menken Salades en Sauzen B.V.",
      "province": "Teylingen",
      "state": "Zuid-Holland",
      "active": false
    },
    {
      "additives": 8,
      "address": "Carretera Calahorra, km 1, 26560 Autol, La Rioja, Spain",
      "address_type": "supplier",
      "allergens": [
        "cerbada",
        "gluten",
        "soja"
      ],
      "category_child1": "PLATOS PREPARADOS",
      "category_child2": "SECOS",
      "category_root": "ALIMENTACION",
      "co2": 2462.62254429062,
      "country": "Spain",
      "date_inserted": "2019-03-29T11:38:15.525103",
      "distance": 246.26225442906204,
      "locality": "Autol",
      "location": {
        "lat": 42.2230042,
        "lon": -2.0055004000000003
      },
      "postal_code": "26560",
      "price": 0.85,
      "price_netto": " 2,02 Euros",
      "price_norm": "1 KILO: 2,02 Euros",
      "product_amount_netto": "420 g",
      "product_brand": "Hacendado",
      "product_description": " GARBANZO RIOJANA (CHORIZO), HACENDADO, BOTE 420 g",
      "product_description_short": "Garbanzos a la riojana cil 420 gr.",
      "product_name": "Garbanzos a la Riojana",
      "product_price_netto": 2.02,
      "product_quantity_netto": "1 KILO",
      "provider_address": "Crta. De Calahorra km. 1 26560 Autol (La Rioja)",
      "provider_ean_id": 8480000261748,
      "provider_name": "Conservas el Cidacos S.A.",
      "province": "La Rioja"
    },
    {
      "additives": 0,
      "address": "24950 Vidanes, León, Spain",
      "address_type": "supplier",
      "allergens": [
        "lactosa",
        "soja"
      ],
      "category_child1": "ARROZ Y LEGUMBRES",
      "category_child2": "LEGUMBRES COCIDAS",
      "category_root": "ALIMENTACION",
      "co2": 2895.1570977024357,
      "country": "Spain",
      "date_inserted": "2019-03-29T11:37:54.044867",
      "distance": 289.5157097702436,
      "locality": "Vidanes",
      "location": {
        "lat": 42.76359850000001,
        "lon": -5.1402749000000005
      },
      "postal_code": 24950,
      "price": 1.15,
      "price_netto": " 3,07 Euros",
      "price_norm": "1 KILO: 3,07 Euros",
      "product_amount_netto": "570 g",
      "product_brand": "Hacendado",
      "product_description": " GARBANZO COCIDO CON ESPINACA, HACENDADO, TARRO 570 g ESCURRIDO 375 g",
      "product_description_short": "Garbanzos con Espinacas Hacendado 570 g",
      "product_name": "Garbanzos con Espinacas",
      "product_price_netto": 3.07,
      "product_quantity_netto": "1 KILO",
      "provider_address": "Pol. Ind. de Cistierna, P-32. 24950 Vidanes - León",
      "provider_country": "España",
      "provider_ean_id": 8480000260130,
      "provider_name": "Selección de Productos Leoneses,SA",
      "province": "León",
      "state": "Castilla y León"
    },
    {
      "additives": 9,
      "address": "24950 Vidanes, León, Spain",
      "address_type": "supplier",
      "allergens": [
        "soja"
      ],
      "category_child1": "ARROZ Y LEGUMBRES",
      "category_child2": "LEGUMBRES COCIDAS",
      "category_root": "ALIMENTACION",
      "co2": 2895.1570977024357,
      "country": "Spain",
      "date_inserted": "2019-03-29T11:37:54.044867",
      "distance": 289.5157097702436,
      "locality": "Vidanes",
      "location": {
        "lat": 42.76359850000001,
        "lon": -5.1402749000000005
      },
      "postal_code": 24950,
      "price": 0.54,
      "price_netto": " 2,57 Euros",
      "price_norm": "1 KILO: 2,57 Euros",
      "product_amount_netto": "295 g",
      "product_brand": "Hacendado",
      "product_description": " GARBANZO COCIDO, HACENDADO, TARRO 314 g ESCURRIDO 210 g",
      "product_description_short": "Garbanzos Hacendado 295 g",
      "product_name": "Garbanzos",
      "product_price_netto": 2.57,
      "product_quantity_netto": "1 KILO",
      "provider_address": "Pol. Ind. de Cistierna, P-32. 24950 Vidanes - León",
      "provider_country": "España",
      "provider_ean_id": 8480000260390,
      "provider_name": "Selección de Productos Leoneses,SA",
      "province": "León",
      "state": "Castilla y León"
    },
    {
      "additives": 4,
      "address": "Mexico",
      "address_type": "origin",
      "allergens": [],
      "category_child1": "ARROZ Y LEGUMBRES",
      "category_child2": "LEGUMBRES SECAS",
      "category_root": "ALIMENTACION",
      "co2": 90339.53749850867,
      "country": "Mexico",
      "date_inserted": "2019-03-29T11:37:54.044867",
      "distance": 9033.953749850867,
      "ingredients": "garbanzos. las legumbres son un componente esencial de la dieta mediterránea. garbanzos",
      "location": {
        "lat": 23.634501,
        "lon": -102.552784
      },
      "price": 2.2,
      "price_norm": "unknown",
      "product_amount_netto": "1 KG",
      "product_brand": "Hacendado",
      "product_description": " GARBANZO MEXICANO, HACENDADO, PAQUETE 1 kg",
      "product_description_short": "Garbanzos Hacendado 1 Kg",
      "product_name": "Garbanzos",
      "provider_address": "Polígono Industrial de Cistierna. 24950 Vidanes - León",
      "provider_country": "México",
      "provider_ean_id": 8480000052148,
      "provider_name": "SEPROLESA"
    },
    {
      "additives": 13,
      "address": "24950 Vidanes, León, Spain",
      "address_type": "supplier",
      "allergens": [
        "gluten",
        "cerbada"
      ],
      "category_child1": "ARROZ Y LEGUMBRES",
      "category_child2": "LEGUMBRES COCIDAS",
      "category_root": "ALIMENTACION",
      "co2": 2895.1570977024357,
      "country": "Spain",
      "date_inserted": "2019-03-29T11:37:54.044867",
      "distance": 289.5157097702436,
      "locality": "Vidanes",
      "location": {
        "lat": 42.76359850000001,
        "lon": -5.1402749000000005
      },
      "postal_code": 24950,
      "price": 0.7,
      "price_netto": " 1,75 Euros",
      "price_norm": "1 KILO: 1,75 Euros",
      "product_amount_netto": "570 g",
      "product_brand": "Hacendado",
      "product_description": " GARBANZO COCIDO, HACENDADO, TARRO 570 g ESCURRIDO 400 g",
      "product_description_short": "Garbanzos Hacendado 570 g",
      "product_name": "Garbanzos",
      "product_price_netto": 1.75,
      "product_quantity_netto": "1 KILO",
      "provider_address": "Pol. Ind. de Cistierna, P-32. 24950 Vidanes - León",
      "provider_country": "España",
      "provider_ean_id": 8480000260291,
      "provider_name": "Selección de Productos Leoneses,SA",
      "province": "León",
      "state": "Castilla y León"
    },
    {
      "additives": 12,
      "address": "Carretera Calahorra, km 1, 26560 Autol, La Rioja, Spain",
      "address_type": "supplier",
      "allergens": [
        "lactosa",
        "soja",
        "cerbada"
      ],
      "category_child1": "PLATOS PREPARADOS",
      "category_child2": "SECOS",
      "category_root": "ALIMENTACION",
      "co2": 2462.62254429062,
      "country": "Spain",
      "date_inserted": "2019-03-29T11:38:15.525103",
      "distance": 246.26225442906204,
      "locality": "Autol",
      "location": {
        "lat": 42.2230042,
        "lon": -2.0055004000000003
      },
      "postal_code": "26560",
      "price": 0.79,
      "price_netto": " 1,88 Euros",
      "price_norm": "1 KILO: 1,88 Euros",
      "product_amount_netto": "420 g",
      "product_brand": "Hacendado",
      "product_description": " GARBANZO JARDINERA, HACENDADO, BOTE 420 g",
      "product_description_short": "Garbanzos a la jardinera cil 420 gr.",
      "product_name": "Garbanzos a la jardinera",
      "product_price_netto": 1.88,
      "product_quantity_netto": "1 KILO",
      "provider_address": "Crta. De Calahorra km. 1 26560 Autol (La Rioja)",
      "provider_ean_id": 8480000261106,
      "provider_name": "Conservas el Cidacos S.A.",
      "province": "La Rioja"
    }
  ]

const basketInit = []


export {productsInit, basketInit};
